/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "YOURPOOLID",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "YOURUSERPOOL",
    "aws_user_pools_web_client_id": "YOURCLIENTID",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "YOURGRAPHQLENDPOINT",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
